name: elevation_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyproj
  - shapely
  - lxml
  - requests
  - tqdm
  - scikit-learn
  - pip:
      - "laspy[lazrs]"
